# Generated by Django 3.1.3 on 2021-01-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unloading',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
