# Generated by Django 3.1.5 on 2021-01-29 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_auto_20210129_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='unloading',
            name='workers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
