# Generated by Django 3.1.5 on 2021-02-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_unloading_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unloading',
            name='alredy_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='unloading',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='unloading',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='unloading',
            name='details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='unloading',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
