# Generated by Django 3.1.3 on 2021-01-25 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserColo',
            new_name='UserColor',
        ),
    ]
