# Generated by Django 3.1.3 on 2021-01-25 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rules', '0006_auto_20210126_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercolor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usercolorcode', to=settings.AUTH_USER_MODEL),
        ),
    ]
